server:
  port: 8081
spring:
  datasource:
    username: admin
    password: 12345678
    url: jdbc:mysql://localhost:3308/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: posters/
base:
  url: "http://localhost:8081"


